name: Gitleaks SAST scan
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: read-all

jobs:
  gitleaks:
    name: Gitleaks SAST scan
    permissions:
      pull-requests: write
    uses: fish-shop/workflows/.github/workflows/gitleaks.yml@3447d9015fbb3eb70b350c9e135731f0b9c65cad # v1.13.51
    secrets:
      gitleaks_license: ${secrets.GITLEAKS_LICENSE}
