name: markdown-links
on:
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  markdown-links:
    permissions:
      pull-requests: write
    uses: fish-shop/workflows/.github/workflows/markdown-links.yml@e58db3ddcda39caaa550d537ac707f97e473fec8 # v1.10.2
