name: release-tags
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

permissions: read-all

jobs:
  release-tags:
    permissions:
      contents: write
    uses: fish-shop/workflows/.github/workflows/release-tags.yml@e58db3ddcda39caaa550d537ac707f97e473fec8 # v1.10.2
